### ISSUE TITLE
Include quality management content

### ISSUE THREAD

**Issue by devbarreto** [devbarreto/quality-management-web-1.0#2]
## Purpose 
- Include text to explain a little about quality management.

### What to do
- [x] Finish dependencies tasks

### Dependencies
- [x]  [Define what topics will be explained](#3)
- [x]  [Create this content](#4)
- [x]  [Include all topics at navigator](#5)
- [x] [Include text about the topic](#6)
